// Generated by Xata Codegen 0.30.0. Please do not edit.
import type { BaseClientOptions, SchemaInference } from "@xata.io/client";
import { buildClient } from "@xata.io/client";
import { env } from "~/env.mjs";

const tables = [] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

// export type DatabaseSchema = {};

// xata db configuration
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL: env.XATA_POSTGRES_URL_HTTPS,
  apiKey: env.XATA_API_KEY,
  branch: env.XATA_BRANCH,
};
export class XataClient extends DatabaseClient {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
